name: FAST-R GitHub Action
description: 'Runs FAST-R on GitHub Actions'
branding:
  icon: box
  color: gray-dark
runs-on: ubuntu-latest
runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  test_folder:
    description: path of the tests folder
    type: string
    default: 'tests'
  test_coverage:
    description: path of the coverage file
    type: string
    default: "coverage.txt"
  lines_file:
    description: name of lines file that will be generated(?)
    type: string
    default: "lines.txt"
  bbox_file:
    description: name of bbox file that will be generated(?)
    type: string
    default: "bbox.txt"
outputs:
  result:
    description: reduced tests

steps:
- uses: actions/checkout@master
- run: echo '::set-output name=action_echo::enabled'
- name: FAST-R GitHub Action
  uses: jrcamelo/fast-r-action@master
  with:
    args: 
      - test_folder
      - test_coverage
      - lines_file
      - bbox_file
- name: FAST-R again?
  with:
    args: 
      - test_folder
      - test_coverage
      - lines_file
      - bbox_file
  run: |
    python3 -m fastr_wrapper ${{github.event.inputs.test_folder}} ${{github.event.inputs.test_coverage}} ${{github.event.inputs.lines_file}}${{github.event.inputs.bbox_file}}> result.txt
    echo '::set-output name=result::$(cat)'
    echo '::set-output name=action_echo::disabled'
