name: FAST-R GitHub Action
description: 'Runs FAST-R on GitHub Actions'
branding:
  icon: box
  color: gray-dark
runs-on: ubuntu-latest
runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  test_folder:
    description: path of the tests folder
    type: string
    default: 'tests'
  test_coverage:
    description: path of the coverage file
    type: string
    default: "coverage.txt"

outputs:
  result:
    description: list of reduced tests

steps:
- uses: actions/checkout@master
- name: FAST-R GitHub Action
  uses: jrcamelo/fast-r-action@master
  with:
    args: 
      - test_folder
      - test_coverage

  # run: |
  #   echo 'running1?'
  #   echo '::set-output name=action_echo::enabled'
  #   python3 -m fastr_wrapper test1 test2 linestest bboxtest > result.txt


