name: FAST-R GitHub Action
description: 'Runs FAST-R and returns a reduced list of tests'
branding:
  icon: box
  color: gray-dark
runs-on: ubuntu-latest
runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  test_folder:
    description: path of the tests folder
    type: string
    default: '/tests'
  test_coverage:
    description: path of the coverage xml file
    type: string
    required: false

outputs:
  result:
    description: list of reduced tests

steps:
- uses: actions/checkout@master
- name: FAST-R GitHub Action
  uses: jrcamelo/fast-r-action@master
  with:
    args: 
      - test_folder
      - test_coverage


