name: FAST-R GitHub Action
description: 'Runs FAST-R on GitHub Actions'
branding:
  icon: box
  color: gray-dark
runs-on: ubuntu-latest
runs:
  using: 'docker'
  image: 'Dockerfile'
steps:
- uses: actions/checkout@master
- name: FAST-R GitHub Action
  uses: jrcamelo/fast-r-action@master
  with:
    args: 
      - 'Test folder path'
      - 'Coverage file path'
      - 'Lines covered file path'
      - 'Blackbox file path'