name: FAST-R Test Reduction for PyTest
description: 'Runs a test reduction algorithm for PyTest projects and returns a reduced list of tests'
branding:
  icon: minimize-2
  color: gray-dark
runs-on: ubuntu-latest
runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  test_folder:
    description: path of the tests folder
    type: string
    default: 'tests/'
    required: true
  test_coverage:
    description: path of the coverage xml file, which the action can generate
    type: string
    required: false

outputs:
  result:
    description: list of reduced tests

steps:
- uses: actions/checkout@master
- name: FAST-R for PyTest
  uses: jrcamelo/fast-r-action@master
  with:
    args: 
      - test_folder
      - test_coverage
- name: Commit report
    run: |
      git config --global user.name 'Your Name'
      git config --global user.email 'your-username@users.noreply.github.com'
      git commit -am "Automated report"
      git push

