name: FAST-R Test Reduction for PyTest
description: 'Runs a test reduction algorithm for PyTest projects and returns a reduced list of tests'
branding:
  icon: minimize-2
  color: gray-dark
runs-on: ubuntu-latest
runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  test_folder:
    description: path of the tests folder
    type: string
    default: 'tests/'
    required: true
  test_coverage:
    description: path of the coverage xml file, which the action can generate
    type: string
    required: false

outputs:
  result:
    description: list of reduced tests

steps:
  - name: step test
    run: echo "Changes have been pushed"
    
  - uses: actions/checkout@v2
  - name: FAST-R for PyTest
    uses: jrcamelo/fast-r-action@master
    with:
      args: 
        - test_folder
        - test_coverage
